name: dart_ping
description: Multi-platform network ping utility for native desktop and android applications.
version: 6.1.1
homepage: https://github.com/point-source/dart_ping

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.4.2

dev_dependencies:
  dart_code_metrics: ^4.8.1
  lints: ^1.0.1
  test: ^1.14.4
