name: dart_ping_ios
description: This package adds iOS support to the dart_ping package via plugin registration.
version: 4.0.2
homepage: https://github.com/point-source/dart_ping
repository: https://github.com/point-source/dart_ping

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_ping: ^9.0.0
  flutter_icmp_ping: ^3.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.14.4
